FROM golang:1.14.2

WORKDIR /go/src/github.com/labd/terraform-contentful

# http://stackoverflow.com/questions/39278756/cache-go-get-in-docker-build
COPY ./install-dependencies.sh /go/src/github.com/labd/terraform-contentful
RUN ./install-dependencies.sh

COPY . /go/src/github.com/labd/terraform-contentful

CMD go test -v