# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install
          command: go get ./contentful
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Test
          command: |
            export TF_ACC=1
            go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./contentful -v ./contentful
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
